name: Automatic Releases

on: [push]
  

jobs:
  releases:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Set up GitHub CLI
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Create a release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        gh release create $(date + '%Y-%m-%d_%H-%M-%S')" --title "Release $(date + '%Y-%m-%d')" --notes "This is an automatic release from CI/CD"


